name: Run Node Check Script and Save Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许提交文件到仓库

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests PySocks

      - name: 安装 Xray 核心
        run: |
          wget -q https://github.com/XTLS/Xray-core/releases/latest/download/xray-linux-64.zip
          unzip -q xray-linux-64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/xray
          rm xray-linux-64.zip
          xray --version

      - name: 运行 test.py
        run: python scripts/ccc/test.py

      - name: 提交结果文件
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add scripts/ccc/results.log scripts/ccc/reachable_nodes.txt
          git commit -m "Stage results.log and reachable_nodes.txt [$(date -u +'%Y-%m-%d %H:%M:%S UTC')]" || echo "No changes to commit"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传日志作为工件
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: scripts/ccc/*.txt
          retention-days: 7
